# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: googlemap.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fgooglemap.proto\x12\tgooglemap\")\n\x16ValidateAddressRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"F\n\x17ValidateAddressResponse\x12\x10\n\x08is_valid\x18\x01 \x01(\x08\x12\x19\n\x11validated_address\x18\x02 \x01(\t2r\n\x16ValidateAddressService\x12X\n\x0fValidateAddress\x12!.googlemap.ValidateAddressRequest\x1a\".googlemap.ValidateAddressResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'googlemap_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VALIDATEADDRESSREQUEST']._serialized_start=30
  _globals['_VALIDATEADDRESSREQUEST']._serialized_end=71
  _globals['_VALIDATEADDRESSRESPONSE']._serialized_start=73
  _globals['_VALIDATEADDRESSRESPONSE']._serialized_end=143
  _globals['_VALIDATEADDRESSSERVICE']._serialized_start=145
  _globals['_VALIDATEADDRESSSERVICE']._serialized_end=259
# @@protoc_insertion_point(module_scope)
